CREATE TABLE t (id INT NOT NULL PRIMARY KEY, n INT);
CREATE INDEX t_n ON t(n);
CREATE TABLE t2 (id INT NOT NULL PRIMARY KEY, s VARCHAR(16));
CREATE TABLE child(cid INT NOT NULL PRIMARY KEY, tid INT, x INT, GROUPING FOREIGN KEY(tid) REFERENCES t(id));
CREATE TABLE p(x INT NOT NULL, UNIQUE(x));
CREATE TABLE x(xid INT NOT NULL PRIMARY KEY, v1 INT);
CREATE TABLE y(yid INT NOT NULL PRIMARY KEY, xid INT, v2 INT, FOREIGN KEY(xid) REFERENCES x(xid) ON UPDATE CASCADE ON DELETE SET NULL);
