# Normal registration
#
PUT     /direct/library?module=test.proc1&language=Javascript @direct-create.body
EQUALS  {"functions":2}\n

# Attempt to register an invalid specification
#
PUT     /direct/library?module=test.proc2&language=Javascript @bad-direct-create.body
CONTAINS Invalid function specification

# Register a script with no _register function
#
PUT     /direct/library?module=test.proc2&language=Javascript @missing-direct-create.body
EQUALS  {"functions":2}\n

# Verify a valid script is still available
#
GET     /direct/call/test.cnames?prefix=SomeParameterValue
EQUALS  SomeParameterValue,John Smith,Willy Jones,Jane Smith,Jonathan Smyth\n

# Try adding broken scripts in a different order
#
DELETE  /direct/library?module=test.proc1
DELETE  /direct/library?module=test.proc2
PUT     /direct/library?module=test.proc1&language=Javascript @missing-direct-create.body
PUT     /direct/library?module=test.proc2&language=Javascript @bad-direct-create.body
PUT     /direct/library?module=test.proc3&language=Javascript @direct-create.body

# Verify a valid script is still available
#
GET     /direct/call/test.cnames?prefix=SomeParameterValue
EQUALS  SomeParameterValue,John Smith,Willy Jones,Jane Smith,Jonathan Smyth\n

