PUT     /direct/library?module=test.proc1&language=Javascript @direct-create.body
EQUALS  {"functions":2}\n
DELETE  /direct/library?module=test.proc1&language=Javascript
EQUALS  {"functions":0}\n
PUT     /direct/library?module=test.proc1&language=Javascript @direct-create.body
GET     /direct/call/test.cnames?prefix=SomeParameterValue
EQUALS  SomeParameterValue,John Smith,Willy Jones,Jane Smith,Jonathan Smyth\n
GET     /direct/call/test.cnames?prefix=SomeOtherParameterValue
EQUALS  SomeOtherParameterValue,John Smith,Willy Jones,Jane Smith,Jonathan Smyth\n
DELETE  /direct/library?module=test.proc1&language=Javascript
GET     /direct/call/test.cnames?prefix=SomeOtherParameterValue
CONTAINS Not Found
