# Install a library with two endpoints
#
PUT     /direct/library?module=test.output_types&language=Javascript @direct-output-types.body
EQUALS  {"functions":4}\n


GET     /direct/call/test.out_string
HEADERS responseCode:200
HEADERS Content-Type:text/plain
EQUALS  correct\n

GET     /direct/call/test.out_json
HEADERS responseCode:200
JSONEQ  {"status":"correct"}
HEADERS Content-Type:application/json

GET     /direct/call/test.out_void
HEADERS responseCode:200
EQUALS  \n
HEADERS Content-Type:application/octet-stream

DEBUG
GET     /direct/call/test.out_void_with_content
HEADERS responseCode:200
EQUALS  \n

PUT     /direct/library?module=test.output_types2&language=Javascript function _register(registrar) {registrar.register("method=GET path=x function=x in=() out=int");};
SHOW
CONTAINS Invalid function specification

PUT     /direct/library?module=test.output_types2&language=Javascript function _register(registrar) {registrar.register("method=GET path=x function=x in=() out=date");};
CONTAINS Invalid function specification

PUT     /direct/library?module=test.output_types2&language=Javascript function _register(registrar) {registrar.register("method=GET path=x function=x in=() out=bytearray");};
CONTAINS Invalid function specification

PUT     /direct/library?module=test.output_types2&language=Javascript function _register(registrar) {registrar.register("method=GET path=x function=x in=() out=float");};
CONTAINS Invalid function specification

