# Install a library with two endpoints
#
PUT     /direct/library?module=test.proc1&language=Javascript @direct-create.body
EQUALS  {"functions":2}\n

# Delete the library
#
DELETE  /direct/library?module=test.proc1&language=Javascript
EQUALS  {"functions":0}\n

# Reinstall it
#
PUT     /direct/library?module=test.proc1&language=Javascript @direct-create.body

# Verify that it runs and consumes the supplied parameter value correctly
#
GET     /direct/call/test.cnames?prefix=SomeParameterValue
EQUALS  SomeParameterValue,John Smith,Willy Jones,Jane Smith,Jonathan Smyth\n
GET     /direct/call/test.cnames?prefix=SomeOtherParameterValue
EQUALS  SomeOtherParameterValue,John Smith,Willy Jones,Jane Smith,Jonathan Smyth\n

# Delete the library#
#
DELETE  /direct/library?module=test.proc1&language=Javascript

# Attempt to invoke end point should return a 404
#
GET     /direct/call/test.cnames?prefix=SomeOtherParameterValue
CONTAINS Not Found
CONTAINS 404
