/**
 * END USER LICENSE AGREEMENT (“EULA”)
 *
 * READ THIS AGREEMENT CAREFULLY (date: 9/13/2011):
 * http://www.akiban.com/licensing/20110913
 *
 * BY INSTALLING OR USING ALL OR ANY PORTION OF THE SOFTWARE, YOU ARE ACCEPTING
 * ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT. YOU AGREE THAT THIS
 * AGREEMENT IS ENFORCEABLE LIKE ANY WRITTEN AGREEMENT SIGNED BY YOU.
 *
 * IF YOU HAVE PAID A LICENSE FEE FOR USE OF THE SOFTWARE AND DO NOT AGREE TO
 * THESE TERMS, YOU MAY RETURN THE SOFTWARE FOR A FULL REFUND PROVIDED YOU (A) DO
 * NOT USE THE SOFTWARE AND (B) RETURN THE SOFTWARE WITHIN THIRTY (30) DAYS OF
 * YOUR INITIAL PURCHASE.
 *
 * IF YOU WISH TO USE THE SOFTWARE AS AN EMPLOYEE, CONTRACTOR, OR AGENT OF A
 * CORPORATION, PARTNERSHIP OR SIMILAR ENTITY, THEN YOU MUST BE AUTHORIZED TO SIGN
 * FOR AND BIND THE ENTITY IN ORDER TO ACCEPT THE TERMS OF THIS AGREEMENT. THE
 * LICENSES GRANTED UNDER THIS AGREEMENT ARE EXPRESSLY CONDITIONED UPON ACCEPTANCE
 * BY SUCH AUTHORIZED PERSONNEL.
 *
 * IF YOU HAVE ENTERED INTO A SEPARATE WRITTEN LICENSE AGREEMENT WITH AKIBAN FOR
 * USE OF THE SOFTWARE, THE TERMS AND CONDITIONS OF SUCH OTHER AGREEMENT SHALL
 * PREVAIL OVER ANY CONFLICTING TERMS OR CONDITIONS IN THIS AGREEMENT.
 */

package com.akiban.sql.test;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.math.BigInteger;
import java.util.Date;
import java.util.Random;

/*
 * creates tests for bitwise math operations
 * */
public class BitwiseMatrixCreator implements Runnable {

    StringBuffer data = new StringBuffer();
    StringBuffer sql_data = new StringBuffer();
    StringBuffer verify = new StringBuffer();
    Random r;
    private int counter = 0;

    /**
     * @param args
     */
    public static void main(String[] args) {
        BitwiseMatrixCreator b = new BitwiseMatrixCreator();
        b.run();
    }

    @Override
    public void run() {
        r = new Random(452342435);
        verify.append("# generated by com.akiban.sql.test.BitwiseMatrixCreator on "
                + new Date() + System.getProperty("line.separator"));
        verify.append("---" + System.getProperty("line.separator")
                + "- Include: all-bitwise-matrix-schema.yaml"
                + System.getProperty("line.separator"));

        data.append("# generated by com.akiban.sql.test.BitwiseMatrixCreator on "
                + new Date() + System.getProperty("line.separator"));
        data.append("# Create a table with all supported data types"
                + System.getProperty("line.separator") + "---"
                + System.getProperty("line.separator")
                + "- CreateTable: bitwise_matrix (" + "        id integer,"
                + "        source1 bigint unsigned,"
                + "        source2 bigint unsigned,"
                + "        bitwise_and bigint," + "        bitwise_or bigint,"
                + "        bitwise_xor bigint,"
                + "        bitwise_rightshift varchar(255),"
                + "        bitwise_leftshift varchar(255),"
                + "        bitwise_invert int" + "        )"
                + System.getProperty("line.separator"));
        sql_data.append("use test;" + System.getProperty("line.separator"));
        sql_data.append("drop Table bitwise_matrix;"
                + System.getProperty("line.separator"));
        sql_data.append("Create Table bitwise_matrix (" + "        id integer,"
                + "        source1 bigint unsigned,"
                + "        source2 bigint unsigned,"
                + "        bitwise_and bigint," + "        bitwise_or bigint,"
                + "        bitwise_xor bigint,"
                + "        bitwise_rightshift varchar(255),"
                + "        bitwise_leftshift varchar(255),"
                + "        bitwise_invert bigint" + "        );"
                + System.getProperty("line.separator"));

        for (int x = 0; x < 25; x++) {
            recordSQL();
        }

        data.append("..." + System.getProperty("line.separator"));
        verify.append("..." + System.getProperty("line.separator"));

        try {
            // will drop the files in the same branch as where this ciode is running
            // sql gets dropped in the root directory of branch
            String path = System.getProperty("user.dir")
                    + "/src/test/resources/com/akiban/sql/pg/yaml/functional/";
            System.out.println(path);
            save(path + "all-bitwise-matrix-schema.yaml", data);
            save("all-bitwise-matrix-schema.sql", sql_data);
            save(path + "test-bitwise-matrix.yaml", verify);
        } catch (IOException e) {
            System.err.println("Error: " + e.getMessage());
        }
    }

    private String genSQL(boolean sql, BigInteger source1, BigInteger source2) {
        String database = "bitwise_matrix";
        if (sql) {
            database = "test." + database;
        }

        return "insert into " + database + " (" + "id," + "source1,"
                + "source2," + "bitwise_and," + "bitwise_or," + "bitwise_xor,"
                + "bitwise_rightshift," + "bitwise_leftshift,"
                + "bitwise_invert" + ") values (" + (counter) + "," + source1
                + "," + source2 + "," + (source1.and(source2)).toString() + ","
                + (source1.or(source2)).toString() + ","
                + (source1.xor(source2)).toString() + ",'"
                + (source1.shiftRight(source2.intValue())) + "','"
                + (source1.shiftLeft(source2.intValue())) + "',"
                + (source1.andNot(source2)) + " )";
    }

    private String returnYAMLselects() {
        return "---"
                + System.getProperty("line.separator")
                + "- Statement: select id,source1,source2,BITAND(source1,source2),BITXOR(source1,source2),BITOR(source1,source2) from bitwise_matrix where "
                + "((BITAND(source1,source2) != bitwise_and) or "
                + "(BITXOR(source1,source2) != bitwise_xor) or "
                + "(BITOR(source1,source2) != bitwise_or)) and id="
                + counter
                + System.getProperty("line.separator")
                + "- row_count: 0"
                + System.getProperty("line.separator")
                + "---"
                + System.getProperty("line.separator")
                + "- Statement: select id,source1,source2 from bitwise_matrix where "
                + "((RIGHTSHIFT(source1,source2) != bitwise_rightshift) or "
                + "(LEFTSHIFT(source1,source2) != bitwise_leftshift)) and id="
                + counter + System.getProperty("line.separator")
                + "- row_count: 0" + System.getProperty("line.separator");
    }

    private void recordSQL() {
        counter++;
        BigInteger source1 = BigInteger.valueOf(r.nextInt(10));
        BigInteger source2 = BigInteger.valueOf(r.nextInt(10));
        data.append("---" + System.getProperty("line.separator")
                + "- Statement: " + genSQL(false, source1, source2)
                + System.getProperty("line.separator"));
        verify.append(returnYAMLselects());
        sql_data.append(genSQL(true, source1, source2) + ";"
                + System.getProperty("line.separator"));
    }

    private void save(String filename, StringBuffer data) throws IOException {
        try {
            // Create file
            FileWriter fstream = new FileWriter(filename);
            BufferedWriter out = new BufferedWriter(fstream);
            out.write(data.toString());
            // Close the output stream
            out.close();
        } catch (Exception e) {// Catch exception if any
            System.err.println("Error: " + e.getMessage());
        }
        File f = new File(filename);
        System.out.println(f.getCanonicalPath());
        System.out.println(data.toString());

    }

}
