/**
 * Copyright (C) 2011 Akiban Technologies Inc.
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses.
 */

package com.akiban.sql.test;

import java.util.Arrays;

import junit.framework.Assert;

import org.junit.Test;

/*
 * Test class for converting MySQL test cases to Yaml format
 * */
public class MySQLTestTranslatorTest extends MySQLTestTranslator {

    @Test
    public void testLargeData() {
        MySQLTestTranslator t = new MySQLTestTranslator();
        String strLine = "";
        strLine = "a\ta\t1";
        t.translateData(strLine);
        strLine = "a\ta\t2";
        t.translateData(strLine);
        strLine = "a\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\ta\t1";
        t.translateData(strLine);
        strLine = "b\ta\t1";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\ta\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t1";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        strLine = "a\tb\t1";
        t.translateData(strLine);
        strLine = "a\tb\t2";
        t.translateData(strLine);
        strLine = "b\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\tb\t1";
        t.translateData(strLine);
        strLine = "b\ta\t1";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\tb\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t1";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        strLine = "a\ta\t3";
        t.translateData(strLine);
        strLine = "a\ta\t2";
        t.translateData(strLine);
        strLine = "a\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\ta\t1";
        t.translateData(strLine);
        strLine = "b\ta\t3";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\ta\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t3";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        strLine = "a\tb\t3";
        t.translateData(strLine);
        strLine = "a\tb\t2";
        t.translateData(strLine);
        strLine = "b\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\tb\t1";
        t.translateData(strLine);
        strLine = "b\ta\t3";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\tb\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t3";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        strLine = "a\ta\t2";
        t.translateData(strLine);
        strLine = "a\ta\t2";
        t.translateData(strLine);
        strLine = "a\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\ta\t1";
        t.translateData(strLine);
        strLine = "b\ta\t2";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\ta\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t2";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        strLine = "a\tb\t2";
        t.translateData(strLine);
        strLine = "a\tb\t2";
        t.translateData(strLine);
        strLine = "b\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\tb\t1";
        t.translateData(strLine);
        strLine = "b\ta\t2";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\tb\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t2";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        strLine = "a\ta\t7";
        t.translateData(strLine);
        strLine = "a\ta\t2";
        t.translateData(strLine);
        strLine = "a\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\ta\t1";
        t.translateData(strLine);
        strLine = "b\ta\t7";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\ta\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        strLine = "a\tb\t7";
        t.translateData(strLine);
        strLine = "a\tb\t2";
        t.translateData(strLine);
        strLine = "b\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\tb\t1";
        t.translateData(strLine);
        strLine = "b\ta\t7";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\tb\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        strLine = "a\ta\t6";
        t.translateData(strLine);
        strLine = "a\ta\t2";
        t.translateData(strLine);
        strLine = "a\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\ta\t1";
        t.translateData(strLine);
        strLine = "b\ta\t6";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\ta\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t6";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        strLine = "a\tb\t6";
        t.translateData(strLine);
        strLine = "a\tb\t2";
        t.translateData(strLine);
        strLine = "b\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\tb\t1";
        t.translateData(strLine);
        strLine = "b\ta\t6";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\tb\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t6";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        strLine = "a\ta\t4";
        t.translateData(strLine);
        strLine = "a\ta\t2";
        t.translateData(strLine);
        strLine = "a\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\ta\t1";
        t.translateData(strLine);
        strLine = "b\ta\t4";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\ta\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t4";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        strLine = "a\tb\t4";
        t.translateData(strLine);
        strLine = "a\tb\t2";
        t.translateData(strLine);
        strLine = "b\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\tb\t1";
        t.translateData(strLine);
        strLine = "b\ta\t4";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\tb\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t4";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        strLine = "a\ta\t5";
        t.translateData(strLine);
        strLine = "a\ta\t2";
        t.translateData(strLine);
        strLine = "a\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\ta\t1";
        t.translateData(strLine);
        strLine = "b\ta\t5";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\ta\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t5";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        strLine = "a\tb\t5";
        t.translateData(strLine);
        strLine = "a\tb\t2";
        t.translateData(strLine);
        strLine = "b\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\tb\t1";
        t.translateData(strLine);
        strLine = "b\ta\t5";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\tb\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t5";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        strLine = "a\ta\t9";
        t.translateData(strLine);
        strLine = "a\ta\t2";
        t.translateData(strLine);
        strLine = "a\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\ta\t1";
        t.translateData(strLine);
        strLine = "b\ta\t9";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\ta\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t9";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        strLine = "a\tb\t9";
        t.translateData(strLine);
        strLine = "a\tb\t2";
        t.translateData(strLine);
        strLine = "b\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\tb\t1";
        t.translateData(strLine);
        strLine = "b\ta\t9";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\tb\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t9";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        strLine = "a\ta\t8";
        t.translateData(strLine);
        strLine = "a\ta\t2";
        t.translateData(strLine);
        strLine = "a\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\ta\t1";
        t.translateData(strLine);
        strLine = "b\ta\t8";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\ta\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t8";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        strLine = "a\tb\t8";
        t.translateData(strLine);
        strLine = "a\tb\t2";
        t.translateData(strLine);
        strLine = "b\tb\t3";
        t.translateData(strLine);
        strLine = "a\tc\t4";
        t.translateData(strLine);
        strLine = "a\td\t5";
        t.translateData(strLine);
        strLine = "b\tb\t1";
        t.translateData(strLine);
        strLine = "b\ta\t8";
        t.translateData(strLine);
        strLine = "b\tc\t6";
        t.translateData(strLine);
        strLine = "b\te\t4";
        t.translateData(strLine);
        strLine = "b\tz\t5";
        t.translateData(strLine);
        strLine = "c\tb\t5";
        t.translateData(strLine);
        strLine = "c\tc\t7";
        t.translateData(strLine);
        strLine = "c\tc\t8";
        t.translateData(strLine);
        strLine = "c\td\t9";
        t.translateData(strLine);
        strLine = "c\tf\t5";
        t.translateData(strLine);
        Assert.assertEquals(270, t.smallCounter);
        char[] test = { 'c', 'f', '5' };
        Assert.assertEquals(Arrays.toString(test),
                Arrays.toString(t.alldata[t.smallCounter - 1]));
        char[] test2 = { 'c', 'd', '9' };
        Assert.assertEquals(Arrays.toString(test2),
                Arrays.toString(t.alldata[t.smallCounter - 2]));
    }

}
