drop schema if exists online_buddies;
create schema online_buddies;
use online_buddies;

CREATE TABLE `user` (
  `uid` bigint(20) NOT NULL AUTO_INCREMENT,
  `accTypeID` int(11) NOT NULL DEFAULT '0',
  `shortLocaleID` varchar(2) DEFAULT NULL,
  `countryCode` decimal(3,0) DEFAULT NULL,
  `uLastUpdated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `username` varchar(30) NOT NULL,
  `password` varchar(128) NOT NULL,
  `passwordHashType` varchar(5) NOT NULL DEFAULT 'md5',
  `email` varchar(255) NOT NULL,
  `userJoinDate` datetime DEFAULT NULL,
  `lastIPAddress` bigint(20) DEFAULT NULL,
  `lastUserAgent` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE KEY `username_key` (`username`),
  KEY `ipAddresses` (`lastIPAddress`),
  KEY `user_agent_key` (`lastUserAgent`),
  KEY `email_key` (`email`),
  KEY `last_login_key` (`userJoinDate`),
  KEY `Ref1775` (`shortLocaleID`),
  KEY `Ref3676` (`countryCode`),
  KEY `Ref4871` (`accTypeID`)
) ENGINE=AkibanDB AUTO_INCREMENT=21915561 DEFAULT CHARSET=utf8;

CREATE TABLE `as_search` (
  `uid` bigint(20) NOT NULL,
  `abuse` varchar(5) NOT NULL DEFAULT '0',
  `emailFrequency` varchar(20) DEFAULT NULL,
  `emailVerified` char(2) DEFAULT 'N',
  `freeToInteract` char(2) DEFAULT 'N',
  `lastLogin` datetime DEFAULT NULL,
  `optOutStatus` char(2) DEFAULT 'N',
  `trackable` char(2) DEFAULT '1',
  `unitType` varchar(20) DEFAULT 'metric',
  PRIMARY KEY (`uid`),
  KEY `idx_abuse` (`abuse`),
  KEY `idx_emailFrequency` (`emailFrequency`),
  KEY `idx_lastLogin` (`lastLogin`),
  CONSTRAINT `__akiban_fk_01` FOREIGN KEY `__akiban_fk_01` (`uid`) REFERENCES `user` (`uid`)
) ENGINE=AkibanDB DEFAULT CHARSET=latin1;


CREATE TABLE `profile_locations` (
  `profileID` bigint(20) NOT NULL,
  `locationID` int(11) NOT NULL,
  `travelID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`profileID`,`locationID`),
  KEY `Ref18116` (`locationID`),
  CONSTRAINT `__akiban_fk_02` FOREIGN KEY `__akiban_fk_02` (`profileID`) REFERENCES `as_search` (`uid`)
) ENGINE=AkibanDB DEFAULT CHARSET=utf8;

CREATE TABLE `online_search` (
  `profileID` bigint(20) NOT NULL,
  `1` char(1) DEFAULT 'N',
  `2` char(1) DEFAULT 'N',
  `3` char(1) DEFAULT 'N',
  `4` char(1) DEFAULT 'N',
  `5` char(1) DEFAULT 'N',
  `6` char(1) DEFAULT 'N',
  `7` char(1) DEFAULT 'N',
  `8` char(1) DEFAULT 'N',
  `9` char(1) DEFAULT 'N',
  `10` char(1) DEFAULT 'N',
  `11` char(1) DEFAULT 'N',
  `12` char(1) DEFAULT 'N',
  `13` char(1) DEFAULT 'N',
  `14` char(1) DEFAULT 'N',
  `15` char(1) DEFAULT 'N',
  `16` char(1) DEFAULT 'N',
  `17` char(1) DEFAULT 'N',
  `18` char(1) DEFAULT 'N',
  `19` char(1) DEFAULT 'N',
  `20` char(1) DEFAULT 'N',
  `21` char(1) DEFAULT 'N',
  `22` char(1) DEFAULT 'N',
  `23` char(1) DEFAULT 'N',
  `24` char(1) DEFAULT 'N',
  `25` char(1) DEFAULT 'N',
  `26` char(1) DEFAULT 'N',
  `27` char(1) DEFAULT 'N',
  `28` char(1) DEFAULT 'N',
  `29` char(1) DEFAULT 'N',
  `30` char(1) DEFAULT 'N',
  `31` char(1) DEFAULT 'N',
  `32` char(1) DEFAULT 'N',
  `33` char(1) DEFAULT 'N',
  `34` char(1) DEFAULT 'N',
  `35` char(1) DEFAULT 'N',
  `36` char(1) DEFAULT 'N',
  `37` char(1) DEFAULT 'N',
  `38` char(1) DEFAULT 'N',
  `39` char(1) DEFAULT 'N',
  `40` char(1) DEFAULT 'N',
  `41` char(1) DEFAULT 'N',
  `42` char(1) DEFAULT 'N',
  `43` char(1) DEFAULT 'N',
  `44` char(1) DEFAULT 'N',
  `45` char(1) DEFAULT 'N',
  `46` char(1) DEFAULT 'N',
  `47` char(1) DEFAULT 'N',
  `48` char(1) DEFAULT 'N',
  `49` char(1) DEFAULT 'N',
  `50` char(1) DEFAULT 'N',
  `51` char(1) DEFAULT 'N',
  `52` char(1) DEFAULT 'N',
  `53` char(1) DEFAULT 'N',
  `54` char(1) DEFAULT 'N',
  `55` char(1) DEFAULT 'N',
  `56` char(1) DEFAULT 'N',
  `57` char(1) DEFAULT 'N',
  `58` char(1) DEFAULT 'N',
  `59` char(1) DEFAULT 'N',
  `60` char(1) DEFAULT 'N',
  `61` char(1) DEFAULT 'N',
  `62` char(1) DEFAULT 'N',
  `63` char(1) DEFAULT 'N',
  `64` char(1) DEFAULT 'N',
  `65` char(1) DEFAULT 'N',
  `66` char(1) DEFAULT 'N',
  `67` char(1) DEFAULT 'N',
  `68` char(1) DEFAULT 'N',
  `69` char(1) DEFAULT 'N',
  `70` char(1) DEFAULT 'N',
  `71` char(1) DEFAULT 'N',
  `72` char(1) DEFAULT 'N',
  `73` char(1) DEFAULT 'N',
  `74` char(1) DEFAULT 'N',
  `75` char(1) DEFAULT 'N',
  `76` char(1) DEFAULT 'N',
  `77` char(1) DEFAULT 'N',
  `78` char(1) DEFAULT 'N',
  `79` char(1) DEFAULT 'N',
  `80` char(1) DEFAULT 'N',
  `81` char(1) DEFAULT 'N',
  `82` char(1) DEFAULT 'N',
  `83` char(1) DEFAULT 'N',
  `84` char(1) DEFAULT 'N',
  `85` char(1) DEFAULT 'N',
  `86` char(1) DEFAULT 'N',
  `87` char(1) DEFAULT 'N',
  `88` char(1) DEFAULT 'N',
  `89` char(1) DEFAULT 'N',
  `90` char(1) DEFAULT 'N',
  `91` char(1) DEFAULT 'N',
  `92` char(1) DEFAULT 'N',
  `93` char(1) DEFAULT 'N',
  `94` char(1) DEFAULT 'N',
  `95` char(1) DEFAULT 'N',
  `96` char(1) DEFAULT 'N',
  `97` char(1) DEFAULT 'N',
  `98` char(1) DEFAULT 'N',
  `99` char(1) DEFAULT 'N',
  `100` char(1) DEFAULT 'N',
  `101` char(1) DEFAULT 'N',
  `102` char(1) DEFAULT 'N',
  `103` char(1) DEFAULT 'N',
  `104` char(1) DEFAULT 'N',
  `105` char(1) DEFAULT 'N',
  `106` char(1) DEFAULT 'N',
  `107` char(1) DEFAULT 'N',
  `108` char(1) DEFAULT 'N',
  `109` char(1) DEFAULT 'N',
  `110` char(1) DEFAULT 'N',
  `111` char(1) DEFAULT 'N',
  `112` char(1) DEFAULT 'N',
  `113` char(1) DEFAULT 'N',
  `114` char(1) DEFAULT 'N',
  `115` char(1) DEFAULT 'N',
  `116` char(1) DEFAULT 'N',
  `117` char(1) DEFAULT 'N',
  `Height` int(11) DEFAULT NULL,
  `Age` int(11) DEFAULT NULL,
  `Girth` int(11) DEFAULT NULL,
  `Length` int(11) DEFAULT NULL,
  `abuse` varchar(5) DEFAULT '0',
  `lastLogin` datetime DEFAULT NULL,
  `isChatSupported` char(1) DEFAULT 'N',
  `isChatEnabled` char(1) DEFAULT 'N',
  `isMobile` char(1) DEFAULT 'N',
  `locationID_level1` int(11) DEFAULT NULL,
  `locationID_level2` int(11) DEFAULT NULL,
  `locationID_level3` int(11) DEFAULT NULL,
  `locationID_level4` int(11) DEFAULT NULL,
  `lat` decimal(14,10) DEFAULT NULL,
  `lon` decimal(14,10) DEFAULT NULL,
  `publicApprovedImageCount` int(11) DEFAULT '0',
  `118` char(1) DEFAULT 'N',
  `username` varchar(30) DEFAULT NULL,
  `position` int(11) DEFAULT '78',
  `build` int(11) DEFAULT '36',
  `ethnicity` int(11) DEFAULT '56',
  `intosBitmask` bigint(20) DEFAULT NULL,
  `xmlmobileLat` double DEFAULT NULL,
  `xmlmobileLon` double DEFAULT NULL,
  `platformID` smallint(6) DEFAULT '0',
  PRIMARY KEY (`profileID`),
  KEY `idx_Height` (`Height`),
  KEY `idx_Age` (`Age`),
  KEY `idx_Girth` (`Girth`),
  KEY `idx_Length` (`Length`),
  KEY `idx_abuse` (`abuse`),
  KEY `idx_lastLogin` (`lastLogin`),
  KEY `idx_isChatSupported` (`isChatSupported`),
  KEY `idx_isChatEnabled` (`isChatEnabled`),
  KEY `idx_isMobile` (`isMobile`),
  KEY `idx_locationID_level1` (`locationID_level1`),
  KEY `idx_locationID_level2` (`locationID_level2`),
  KEY `idx_locationID_level3` (`locationID_level3`),
  KEY `idx_locationID_level4` (`locationID_level4`),
  KEY `idx_publicApprovedImageCount` (`publicApprovedImageCount`),
  KEY `idx_username` (`username`),
  KEY `idx_position` (`position`),
  KEY `idx_build` (`build`),
  KEY `idx_ethnicity` (`ethnicity`),
  KEY `idx_os_platformID` (`platformID`),
  KEY `idx_intosBitmask` (`intosBitmask`),
  CONSTRAINT `__akiban_fk_03` FOREIGN KEY `__akiban_fk_03` (`profileID`) REFERENCES `as_search` (`uid`)
) ENGINE=AkibanDB DEFAULT CHARSET=latin1;

CREATE TABLE `region_children` (
  `rid` int(11) NOT NULL DEFAULT '0',
  `v2childstring` varchar(255) DEFAULT NULL,
  `locid` int(11) NOT NULL DEFAULT '0',
  `regionFullName` varchar(255) NOT NULL DEFAULT '',
  `lastmod_ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `rid_locid_uniq` (`rid`,`locid`),
  KEY `loc_key` (`locid`)
) ENGINE=AkibanDB DEFAULT CHARSET=utf8;

CREATE INDEX olb_non_group ON profile_locations(locationID, profileID);
