CREATE TABLE t (id INT NOT NULL PRIMARY KEY, n INT);
CREATE INDEX t_n ON t(n);
CREATE TABLE t2 (id INT NOT NULL PRIMARY KEY, s VARCHAR(16));
CREATE TABLE child(cid INT NOT NULL PRIMARY KEY, tid INT, x INT, GROUPING FOREIGN KEY(tid) REFERENCES t(id));
CREATE TABLE p(x INT NOT NULL, UNIQUE(x));
