/**
 * END USER LICENSE AGREEMENT (“EULA”)
 *
 * READ THIS AGREEMENT CAREFULLY (date: 9/13/2011):
 * http://www.akiban.com/licensing/20110913
 *
 * BY INSTALLING OR USING ALL OR ANY PORTION OF THE SOFTWARE, YOU ARE ACCEPTING
 * ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT. YOU AGREE THAT THIS
 * AGREEMENT IS ENFORCEABLE LIKE ANY WRITTEN AGREEMENT SIGNED BY YOU.
 *
 * IF YOU HAVE PAID A LICENSE FEE FOR USE OF THE SOFTWARE AND DO NOT AGREE TO
 * THESE TERMS, YOU MAY RETURN THE SOFTWARE FOR A FULL REFUND PROVIDED YOU (A) DO
 * NOT USE THE SOFTWARE AND (B) RETURN THE SOFTWARE WITHIN THIRTY (30) DAYS OF
 * YOUR INITIAL PURCHASE.
 *
 * IF YOU WISH TO USE THE SOFTWARE AS AN EMPLOYEE, CONTRACTOR, OR AGENT OF A
 * CORPORATION, PARTNERSHIP OR SIMILAR ENTITY, THEN YOU MUST BE AUTHORIZED TO SIGN
 * FOR AND BIND THE ENTITY IN ORDER TO ACCEPT THE TERMS OF THIS AGREEMENT. THE
 * LICENSES GRANTED UNDER THIS AGREEMENT ARE EXPRESSLY CONDITIONED UPON ACCEPTANCE
 * BY SUCH AUTHORIZED PERSONNEL.
 *
 * IF YOU HAVE ENTERED INTO A SEPARATE WRITTEN LICENSE AGREEMENT WITH AKIBAN FOR
 * USE OF THE SOFTWARE, THE TERMS AND CONDITIONS OF SUCH OTHER AGREEMENT SHALL
 * PREVAIL OVER ANY CONFLICTING TERMS OR CONDITIONS IN THIS AGREEMENT.
 */

package com.akiban.server.types;

import com.akiban.server.error.AkibanInternalException;

import static com.akiban.server.types.AkType.UnderlyingType.*;

public enum AkType {
    DATE(LONG_AKTYPE),
    DATETIME(LONG_AKTYPE),
    DECIMAL(OBJECT_AKTYPE),
    DOUBLE(DOUBLE_AKTYPE),
    FLOAT(FLOAT_AKTYPE),
    INT(LONG_AKTYPE),
    LONG(LONG_AKTYPE),
    VARCHAR(OBJECT_AKTYPE),
    TEXT(OBJECT_AKTYPE),
    TIME(LONG_AKTYPE),
    TIMESTAMP(LONG_AKTYPE),
    U_BIGINT(OBJECT_AKTYPE),
    U_DOUBLE(DOUBLE_AKTYPE),
    U_FLOAT(FLOAT_AKTYPE),
    U_INT(LONG_AKTYPE),
    VARBINARY(OBJECT_AKTYPE),
    YEAR(LONG_AKTYPE),
    BOOL(BOOLEAN_AKTYPE),
    INTERVAL_MILLIS(LONG_AKTYPE),
    INTERVAL_MONTH(LONG_AKTYPE),
    RESULT_SET(OBJECT_AKTYPE),
    NULL(null),
    UNSUPPORTED(null),
    ;

    public UnderlyingType underlyingTypeOrNull() {
        return underlyingType;
    }
    
    public UnderlyingType underlyingType() {
        if (underlyingType == null) {
            throw new AkibanInternalException("no underlying type for " + name());
        }
        return underlyingType;
    }

    private AkType(UnderlyingType underlyingType) {
        this.underlyingType = underlyingType;
    }

    private final UnderlyingType underlyingType;

    public enum UnderlyingType {
        BOOLEAN_AKTYPE,
        LONG_AKTYPE,
        FLOAT_AKTYPE,
        DOUBLE_AKTYPE,
        OBJECT_AKTYPE
    }
}