
package com.akiban.ais.model;

import java.util.ArrayList;
import java.util.List;

public class PrimaryKey
{
    public List<Column> getColumns()
    {
        if (columns == null) {
            columns = new ArrayList<>();
            for (IndexColumn indexColumn : index.getKeyColumns()) {
                columns.add(indexColumn.getColumn());
            }
        }
        return columns;
    }

    public TableIndex getIndex()
    {
        return index;
    }

    /**
     * Indicates whether this primary key was generated by Akiban and is not part of the declared schema.
     * @return true if this primary key was generated by Akiban and is not part of the declared schema, false
     * otherwise.
     */
    public boolean isAkibanPK()
    {
        return getColumns().size() == 1 && getColumns().get(0).isAkibanPKColumn();
    }

    public PrimaryKey(TableIndex index)
    {
        this.index = index;
    }

    private final TableIndex index;
    private List<Column> columns;
}
