CREATE TABLE C1 
(
    cid int not null primary key generated by default as identity,
    name varchar(32) not null
);

 CREATE TABLE C2 
 (
    cid int not null primary key generated always as identity,
    name varchar(32) not null
 );
 

 CREATE TABLE c3
 (
    name varchar(32) not null, 
    address varchar(64) not null,
    cid int not null primary key
);


CREATE TABLE c4
(
    cid int not null, 
    oid int not null,
    items int not null,
    primary key (cid, oid)
);    
