CREATE TABLE addresses
(
  aid int NOT NULL generated by default as identity primary key, 
  cid int NOT NULL,
  state CHAR(2),
  city VARCHAR(100)
);
CREATE INDEX state ON addresses(state);
CREATE SEQUENCE sequence1 start with 1 increment by 1;