CREATE TABLE t1(x INT NOT NULL, y VARCHAR(7), z DECIMAL);
CREATE TABLE t2(w CHAR(1) NOT NULL, z DECIMAL);
CREATE TABLE parent(id INT NOT NULL, PRIMARY KEY(id), name VARCHAR(256) NOT NULL, UNIQUE(name), state CHAR(2));
CREATE TABLE child(id INT NOT NULL, PRIMARY KEY(id), pid INT, GROUPING FOREIGN KEY(pid) REFERENCES parent(id), name VARCHAR(256) NOT NULL);
