create table customers (
	customer_id int not null primary key generated by default as identity,
	customer_name varchar(255) not null,
	customer_title varchar(5),
	primary_payment_code char(4) not null default 'CHRG',
	payment_status char(1) not null default 'C',
	comment varchar(255)
);

CREATE TABLE addresses
(
  aid int NOT NULL generated by default as identity primary key, 
  cid int NOT NULL,
  state CHAR(2),
  city VARCHAR(100)
);
CREATE INDEX state ON addresses(state);

CREATE TABLE orders
(
	order_id int not null primary key generated by default as identity,
	customer_id int not null,
	order_lines int not null default 0,
	order_total double not null default 0.0,
	order_tax decimal (6,3) not null default 0.0
);
