CREATE TABLE t1(c1 INT, c2 INT, c3 INT);
CREATE TABLE t2(c1 INT, c2 INT, c3 INT);
CREATE TABLE t3(c1 INT, c2 INT, c3 INT);
CREATE TABLE t4(c1 INT, c2 INT, c3 INT);
CREATE TABLE t5(c1 INT, c2 INT, c3 INT);
CREATE TABLE t6(c1 INT, c2 INT, c3 INT);
