# Install a library
#
PUT /direct/library?module=test.updates1&language=javascript @direct-update.body
EQUALS  {"functions":3}\n

# Verify data access
#
GET     /direct/call/test.cnames?prefix=SomeParameterValue
EQUALS  SomeParameterValue,John Smith,Willy Jones,Jane Smith,Jonathan Smyth\n

# Insert a new customer
#
PUT     /direct/call/test.cadd/5 {"name":"Mary Johnson"}
HEADERS responseCode:204

GET     /direct/call/test.cnames?prefix=SomeParameterValue
EQUALS  SomeParameterValue,John Smith,Willy Jones,Jane Smith,Jonathan Smyth,Mary Johnson\n

# Modify customer name
#
POST    /direct/call/test.cchange {"cid":5, "name":"Mary Johnston"}
HEADERS responseCode:204
GET     /direct/call/test.cnames?prefix=SomeParameterValue
EQUALS  SomeParameterValue,John Smith,Willy Jones,Jane Smith,Jonathan Smyth,Mary Johnston\n

# Cause a duplicate key error
#
PUT     /direct/call/test.cadd/5 {"name":"Mary Johnson"}
CONTAINS Duplicate key
HEADERS responseCode:409


