#!/bin/bash

# Move new files into place if no current
DIR="/usr/local/etc/foundationdb/sql"
for f in "${DIR}"/*.new; do
    WITHOUT_NEW="${f%.new}"
    if [ ! -f "${WITHOUT_NEW}" ]; then
        mv "${f}" "${WITHOUT_NEW}"
    fi
done

/bin/launchctl load -w /Library/LaunchDaemons/com.foundationdb.layer.sql.plist

exit 0
