#!/bin/bash

# Stop running service
if [ -f /Library/LaunchDaemons/com.foundationdb.layer.sql.plist ]; then
    /bin/launchctl unload /Library/LaunchDaemons/com.foundationdb.layer.sql.plist || :
fi

exit 0
