#!/bin/sh

mysql -u root <<EOF
use akiban_information_schema;
select '-------------------- types --------------------' as '';
select * from types order by type_name;
select '-------------------- tables --------------------' as '';
select * from tables order by schema_name, table_name;
select '-------------------- groups --------------------' as '';
select * from groups order by group_name;
select '-------------------- columns --------------------' as '';
select * from columns order by schema_name, table_name, column_name;
select '-------------------- indexes --------------------' as '';
select * from indexes order by schema_name, table_name, index_name;
select '-------------------- index_columns --------------------' as '';
select * from index_columns order by schema_name, table_name, index_name, column_name;
EOF
