CREATE TABLE types (
    bigint_field bigint,
    bigint_unsigned_field bigint unsigned,
    blob_field blob,
    boolean_field boolean,
    char_field char(32),
    clob_field clob,
    date_field date,
    datetime_field datetime,
    decimal_field decimal(10,2),
    decimal_big_field decimal(20,6),
    double_field double,
    float_field float,
    integer_field integer,
    smallint_field smallint,
    time_field time,
    timestamp_field timestamp,
    tinyint_field tinyint,
    varchar_field varchar(32),
    year_field year
);
