#!/bin/bash
#
# /etc/init.d/fdb-sql-layer
#
# Startup script for $NAME
# 
# chkconfig: 2345 20 80
# description: Starts and stops $NAME

. /etc/rc.d/init.d/functions

export JAR_FILE=/usr/share/foundationdb-sql/foundationdb-sql-layer.jar
export DEP_DIR=/usr/share/foundationdb-sql/server
export FDBSQL_CONF=/etc/foundationdb-sql
export FDBSQL_HOME=/usr/share/foundationdb-sql
export FDBSQL_OWNR="foundationdb-sql"
NAME="FoundationDB SQL Layer"
log_file=/var/log/foundationdb-sql/layer_stdout.log
pid_file=/var/run/foundationdb-sql/layer.pid
timeout=60
FDBSQL_PROG=/usr/sbin/fdbsqllayer

# Use LSB init script functions for printing messages, if possible
lsb_functions="/lib/lsb/init-functions"
if test -f $lsb_functions ; then
  . $lsb_functions
else
  log_success_msg()
  {
    echo " SUCCESS! $@"
  }
  log_failure_msg()
  {
    echo " ERROR! $@"
  }
fi

# Read configuration variable file if it is present
[ -r /etc/default/fdb-sql-layer ] && . /etc/default/fdb-sql-layer

check_no_process()
{
    if [ ! -e "$pid_file" ]; then
        check_pid=`pgrep -f "cp $JAR_FILE"`
        if [ "$check_pid" != "" ]; then
            return 1
        fi
    fi
    return 0
}

case "$1" in
    start)
        if [ -f $pid_file ]; then
            status -p $pid_file foundationdb-sql
            exit 1
        fi
        check_no_process
        if [ $? -ne 0 ]; then
            log_failure_msg "$NAME is already running but no pidfile exists"
            exit 1
        fi
        su $FDBSQL_OWNR -c "$FDBSQL_PROG -p $pid_file -j $JAR_FILE -d $DEP_DIR -c $FDBSQL_CONF" > $log_file 2>&1
        if [ $? -ne 0 ]; then
            log_failure_msg "Starting $NAME"
        fi
        # we give server 60 seconds to start all services
        echo -n "Starting $NAME "
        attempts=1
        while [ ! -f $pid_file ]
        do
            attempts=$(($attempts+1))
            echo -n "."
            if [ $attempts = $timeout ]; then
                break
            fi
            sleep 1
        done
        if [ -f $pid_file ]; then
            log_success_msg
        else
            log_failure_msg
        fi
        ;;
    stop)
        status -p $pid_file foundationdb-sql > /dev/null 2>&1
        retval=$?
        if [ ${retval} -ne 0 ]; then
            # return codes from status as documented in LSB spec
            # http://refspecs.linuxbase.org/LSB_4.0.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
            case ${retval} in
            1) 
              log_failure_msg "$NAME is not running, but PID file exists"
              ;;
            3) 
              log_failure_msg "$NAME process is not running"
              ;;
            *)
              log_failure_msg "Shutdown $NAME"
              ;;
            esac
            exit 1
        fi
        echo -n "Shutdown $NAME "
        su $FDBSQL_OWNR -c "kill `cat $pid_file`"
        # we give server 60 seconds to shut down
        attempts=1
        while [ -f $pid_file ]
        do
            attempts=$(($attempts+1))
            echo -n "."
            if [ $attempts = $timeout ]; then
                break
            fi
            sleep 1
        done
        if [ -f $pid_file ]; then
            log_failure_msg
        else
            log_success_msg
        fi
        ;;
    reload|restart)
        $0 stop
        sleep 5
        $0 start
        ;;
    status)
        check_no_process
        if [ $? -ne 0 ]; then
            echo "$NAME is running (pid $check_pid) but no pidfile exists"
            exit 1
        fi
        status -p $pid_file foundationdb-sql
        ;;
    *)
        echo "Usage: `basename $0` start|stop|status|restart|reload"
        exit 1
esac

exit 0

